name: CI/CD Deploy Java App to Tomcat10 on EC2
# Trigger deployment on push to master branch
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3
      # 2 Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      # 3 Build WAR file
      - name: Build WAR file
        run: mvn clean package -DskipTests
      # 4 Verify WAR file exists
      - name: Verify WAR file
        run: |
          echo "=== Listing target directory ==="
          ls -la target/
          echo "=== Checking for WAR files ==="
          if ls target/*.war 1> /dev/null 2>&1; then
            echo "Found WAR files:"
            ls -la target/*.war
            WAR_FILE=$(ls target/*.war | head -1)
            echo "WAR file: $WAR_FILE"
            if [ -d "$WAR_FILE" ]; then
            echo "ERROR: $WAR_FILE is a directory, not a file!"
            exit 1
            fi
            cp "$WAR_FILE" ./ROOT.war
            echo "WAR_FILE copied to ./ROOT.war"
          else
            echo "ERROR: No WAR files found in target directory"
            exit 1
          fi
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Upload WAR to EC2
        run: |
          echo "=== Cleaning up EC2 ==="
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} \
            "sudo rm -rf /tmp/ROOT.war; sudo touch /tmp/ROOT.war; sudo chmod 666 /tmp/ROOT.war"
          echo "=== Uploading WAR file ==="
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ./ROOT.war ubuntu@${{ secrets.EC2_HOST }}:/tmp/ROOT.war
      - name: Verify file copied to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Checking /tmp directory ==="
            ls -la /tmp/
            echo "=== Verifying ROOT.war file ==="
            if [ -f "/tmp/ROOT.war" ]; then
              echo "Found ROOT.war file in /tmp:"
              ls -la /tmp/ROOT.war
              file /tmp/ROOT.war
              if [ ! -f "/tmp/ROOT.war" ]; then
name: CI/CD Deploy Java App to Tomcat10 on EC2
# Trigger deployment on push to master branch
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3
      # 2 Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      # 3 Build WAR file
      - name: Build WAR file
        run: mvn clean package -DskipTests
      # 4 Verify WAR file exists
      - name: Verify WAR file
        run: |
          echo "=== Listing target directory ==="
          ls -la target/
          echo "=== Checking for WAR files ==="
          if ls target/*.war 1> /dev/null 2>&1; then
            echo "Found WAR files:"
            ls -la target/*.war
            WAR_FILE=$(ls target/*.war | head -1)
            echo "WAR file: $WAR_FILE"
            if [ -d "$WAR_FILE" ]; then
            echo "ERROR: $WAR_FILE is a directory, not a file!"
            exit 1
            fi
            cp "$WAR_FILE" ./ROOT.war
            echo "WAR_FILE copied to ./ROOT.war"
          else
            echo "ERROR: No WAR files found in target directory"
            exit 1
          fi
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Upload WAR to EC2
        run: |
          echo "=== Cleaning up EC2 ==="
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} \
            "sudo rm -rf /tmp/ROOT.war; sudo touch /tmp/ROOT.war; sudo chmod 666 /tmp/ROOT.war"
          echo "=== Uploading WAR file ==="
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ./ROOT.war ubuntu@${{ secrets.EC2_HOST }}:/tmp/ROOT.war
      - name: Verify file copied to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Checking /tmp directory ==="
            ls -la /tmp/
            echo "=== Verifying ROOT.war file ==="
            if [ -f "/tmp/ROOT.war" ]; then
              echo "Found ROOT.war file in /tmp:"
              ls -la /tmp/ROOT.war
              file /tmp/ROOT.war
              if [ ! -f "/tmp/ROOT.war" ]; then
                echo "ERROR: /tmp/ROOT.war is not a regular file!"
                exit 1
              fi
            else
              echo "ERROR: /tmp/ROOT.war not found!"
              echo "Contents of /tmp:"
              ls -la /tmp/
              exit 1
            fi
      - name: Deploy WAR on Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Starting Deployment ==="
            echo "1. Stopping Tomcat..."
            sudo systemctl stop tomcat10 || true
            echo "2. Cleaning up old deployment..."
            ls -la /var/lib/tomcat10/webapps/
            sudo systemctl status tomcat10 --no-pager
            echo "=== Deployment Completed Successfully ==="
